### PR TITLE
added an executable with the newer version

### PR DESCRIPTION
**Pull request by jwansek**
Made the newer version into an executable. Added a function in the app that finds assets, using [this](https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile) method. If re-using the .spec file, be sure to change the pathex to your one. Cleaned up files in the repo.
image

### CODE REVIEW

**Comment by thomaskellough** [comment]
This is great! I just finished making one for myself and was about to post it. When I get access to my Mac later I'll add an executable for that.

**Comment by jwansek** [comment]
Happy to help. Including assets is with pyinstaller is such a pain but it's worth it in the end. Good luck with the Mac version!

**Comment by jwansek** [comment]
Pressed the wrong button lol

**Comment by thomaskellough** [comment]
Lmao.

Yea I’m at work with horrible WiFi. Hard for me to do anything correct here.

**Pull request closed without merging**
